#!/bin/bash

### BEGIN INIT INFO
# Provides:          jasp_server  
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop Jasper Report Server
### END INIT INFO

JASP_DIR=/home/bayo/da/testenv
JASP_SERVER_DIR=$JASP_DIR/jaspServer/bin
JASP_SERVER_SCRIPT=$JASP_SERVER_DIR/jasp_server.sh

start()
{
    $JASP_SERVER_SCRIPT start
}

stop()
{
    $JASP_SERVER_SCRIPT stop
}

status()
{
    $JASP_SERVER_SCRIPT status
}

case "$1" in

    'start')
        start
        ;;

    'stop')
        stop
        ;;

    'restart')
        stop
        start
        ;;

    'status')
        status
        ;;

    *)
        echo "Usage: $0 { start | stop | restart | status }"
        exit 1
        ;;
esac

